// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUmXxnutUXm47mVeQQe8WgwWb1dodzTb0',
    appId: '1:9408683174:android:d0f11e339b08815e1da867',
    messagingSenderId: '9408683174',
    projectId: 'dev-odyssey-109b2',
    storageBucket: 'dev-odyssey-109b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvqm8xBMWFum_KIZzeROfIDRDMQgA4VN0',
    appId: '1:9408683174:ios:fb132d041206f4d31da867',
    messagingSenderId: '9408683174',
    projectId: 'dev-odyssey-109b2',
    storageBucket: 'dev-odyssey-109b2.appspot.com',
    androidClientId: '9408683174-9arbvp8r1gvmi9gtpvrnt3j8omj5htfe.apps.googleusercontent.com',
    iosClientId: '9408683174-2tgg8giojb736qi2sa2rnf90rsj7bjkb.apps.googleusercontent.com',
    iosBundleId: 'io.terracorp.devOdyssey',
  );
}
